on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: ittam-back

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle (skip Test)
        run: ./gradlew build -x test
        shell: bash

